{% set name = "yjs-widgets" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yjs_widgets-{{ version }}.tar.gz
  sha256: 31448f51b3f16c8e6790c613630a280ecb22761c4b790f218eefabde27bde472

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - yarn =3
    - hatchling
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - jupyterlab >=4.0.0,<5
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - jupyterlab >=4,<5
    - python {{ python_min }}
  imports:
    - yjs_widgets
  commands:
    - pip check
    # labextensions
    - jupyter labextension list  # [unix]
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - cat labextensions | grep "yjs-widgets.*OK"  # [unix]

about:
  home: https://github.com/davidbrochart/yjs-widgets
  summary: 'A JupyterLab extension for widgets based on Yjs'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/davidbrochart/yjs-widgets

extra:
  recipe-maintainers:
    - davidbrochart
    - trungleduc
    - martinRenou
