{% set name = "yjs-widgets" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yjs_widgets-{{ version }}.tar.gz
  sha256: d2d91965c1d83c8a32bc0378d7c03540d9da18f1675a7c57505c50461c0ac5b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - yarn =3
    - hatchling
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - jupyterlab >=4.0.0,<5
  run:
    - python >=3.6

test:
  requires:
    - pip
    - jupyterlab >=4,<5
  imports:
    - yjs_widgets
  commands:
    - pip check
    # labextensions
    - jupyter labextension list  # [unix]
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - cat labextensions | grep "yjs-widgets.*OK"  # [unix]

about:
  home: https://github.com/davidbrochart/yjs-widgets
  summary: 'A JupyterLab extension for widgets based on Yjs'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/davidbrochart/yjs-widgets

extra:
  recipe-maintainers:
    - davidbrochart
    - trungleduc
    - martinRenou
