schema_version: 1

context:
  name: yjs-widgets
  version: "0.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/yjs_widgets-${{ version }}.tar.gz
  sha256: d7868f3facdad1b68979ce8dab5534c8cfaf681c285d4f01b1986afd0c50ebfe

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - yarn =3
    - hatchling
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - jupyterlab >=4.0.0,<5
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - yjs_widgets
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - jupyterlab >=4,<5
        - python ==${{ python_min }}
    script:
      - if: unix
        then:
          - jupyter labextension list
          - jupyter labextension list 1>labextensions 2>&1
          - cat labextensions | grep "yjs-widgets.*OK"

about:
  summary: A JupyterLab extension for widgets based on Yjs
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/QuantStack/yjs-widgets
  repository: https://github.com/QuantStack/yjs-widgets

extra:
  recipe-maintainers:
    - davidbrochart
    - trungleduc
    - martinRenou
